# Задание к уроку 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [2]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme()

A = np.random.randint(0, 100, size=(200, 50))
A

array([[67, 30, 79, ..., 88, 22, 44],
       [70, 16, 16, ..., 10, 26, 83],
       [97,  5, 93, ..., 64, 94, 31],
       ...,
       [54, 30,  0, ...,  1, 65, 30],
       [84, 44, 71, ..., 97, 63, 95],
       [97, 17, 29, ..., 38, 22, 26]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

array([[42,  8, 44, ..., 65, 77, 69],
       [45, 28, 17, ..., 91, 26, 52],
       [21, 96, 93, ..., 52, 27, 81],
       ...,
       [68, 19, 61, ..., 21, 19, 51],
       [ 6, 17, 28, ...,  4, 31, 98],
       [77, 10, 18, ..., 83, 82, 25]])

# Задание 2.2 (5 баллов)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

In [65]:
B = A[:,::2]
C = A[:,1::2]
B = B.sum(axis=1)
D = C.sum(axis=1)
D = D.mean()
E = B - D
E = np.where(E > 0, 1, -1)
L = list(E)
L *= 50
M = np.array(L)
M = M.reshape(50,200)
M= M.T
N = A*M
N = N[N.min(axis=1)>=0]
N,N.shape
# первый вариант, через умножение на новую матрицу

(106, 50)

In [67]:
B = A[((A[:,::2].sum(axis=1))-(A[:,1::2].sum(axis=1).mean()))>0]
B, B.shape
# как можно это всё сократить)

(array([[67, 30, 79, ..., 88, 22, 44],
        [58, 76, 33, ..., 13, 48, 99],
        [11, 20, 91, ..., 73, 11, 46],
        ...,
        [54, 30,  0, ...,  1, 65, 30],
        [84, 44, 71, ..., 97, 63, 95],
        [97, 17, 29, ..., 38, 22, 26]]),
 (106, 50))

In [60]:
E[E == 1].shape
# проверка - через количество строк, подходящих под условия

(106,)

# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [97]:
B = A.max(axis=1) - A.min(axis=1)
B = np.where(B == 99, B, 0)
np.asarray(B).nonzero()
# готово





(array([  3,   8,  14,  20,  23,  29,  32,  39,  41,  45,  49,  56,  57,
         59,  66,  87, 126, 135, 141, 143, 144, 145, 147, 155, 156, 169,
        178, 180, 184, 190, 193, 195, 198], dtype=int64),)

# Задание 2.4 (7 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

In [101]:
B = np.argsort(A)
B.shape
# не готово

(200, 50)

# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массивы, в каждой строке которого максимальный элементы равен $1$, минимальный - $0$. 

In [113]:
B = (A - A.min())/(A.max() - A.min())
B, B.shape
#готово

(array([[0.42424242, 0.08080808, 0.44444444, ..., 0.65656566, 0.77777778,
         0.6969697 ],
        [0.45454545, 0.28282828, 0.17171717, ..., 0.91919192, 0.26262626,
         0.52525253],
        [0.21212121, 0.96969697, 0.93939394, ..., 0.52525253, 0.27272727,
         0.81818182],
        ...,
        [0.68686869, 0.19191919, 0.61616162, ..., 0.21212121, 0.19191919,
         0.51515152],
        [0.06060606, 0.17171717, 0.28282828, ..., 0.04040404, 0.31313131,
         0.98989899],
        [0.77777778, 0.1010101 , 0.18181818, ..., 0.83838384, 0.82828283,
         0.25252525]]),
 (200, 50))

# Задание 2.6 (2 балла)

Сгенерируйте новый трехмерный массив, размерности $10 \times 200 \times 50$. Подмассивы по нулевой оси должны состоять из элементов `A`, умноженных на $1 - 10$ соответственно

# Задание 2.7 (2 балла)

Создайте новый массив, такой же размерности, как и `A`, в котором сначала сгруппированы четные столбцы `A`, потом  нечетные. Используйте [np.concat()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) 

In [103]:
B = A[:,0::2]
C = A[:,1::2]
# тоже вариант np.hstack((B, C))
np.concatenate((B, C), axis=0)
# готово

array([[42, 44, 87, ...,  5, 44, 77],
       [45, 17,  2, ..., 94, 45, 26],
       [21, 93, 50, ..., 49, 24, 27],
       ...,
       [19, 92, 84, ..., 53, 21, 51],
       [17, 71, 25, ..., 43,  4, 98],
       [10, 41, 56, ..., 70, 83, 25]])

# Задание 2.8 (2 балла)

Посчитайте количество строк массива `A`, в который все элементы больше 5. Используйте [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html) 

In [228]:
B1 = np.all(A, axis=1, keepdims=1)
B2 = np.all(A, axis=1, keepdims=2)
B3 = np.all(A, axis=1, keepdims=3)
B4 = np.all(A, axis=1, keepdims=4)
B5 = np.all(A, axis=1, keepdims=5)
B = B1 * B2 * B3 * B4 * B5
B, A[0]
# не готово




(array([[ True],
        [False],
        [ True],
        [False],
        [False],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [ True],
        [False],
        [ True],
        [False],
        [False],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [False],
        [ True],
        [ True],
        [False],
        [False],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [False],
        [False],
        [False],
        [ True],
        [False],
        [False],
        [False],
        [ True

# Задание 2.9 (2 балла)

Поделите массив `A` горизонтально на 10 частей и создайте новый массив размерности $20 \times 50$, который является средним этих частей. Используйте [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [42]:
B = np.split(A, 10, axis=0)
C = B[5]
C.shape
# готово

(20, 50)

# Задание 2.10 (4 балла)

"Разверните" массив `A` в одномерный массив. Оставьте в нём только уникальные элементы в том же порядке, в котором они встречаются в массиве. Используйте [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

In [218]:
B = A.reshape(1,-1)
C = np.unique(B, return_index = True, return_inverse=True, return_counts=True)
C


# не готово

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([ 58,  25,  54,  71,  30,  33, 161, 200,   1, 143,  89,  55,   3,
          7,  64,  81, 129,  52, 135,   5, 345,  15, 204,  87,  76, 165,
         98,  56,  27,  11, 159, 103, 125,  43,  65, 309,  88, 123, 186,
         20,  31,  17,   0, 141,   2,  50,  38,  37, 389,  82,  36,  68,
         83, 176, 164, 124,  10,   9,  14, 128, 118,  80,  40, 190, 199,
         47,  13,   6, 185,  18,  78, 397,  12, 233,  91,  53,  92,  48,
        259, 153, 138,  23, 162,  45, 155, 178, 151,   4, 274, 330,  16,
         97, 198,  39,  22, 212,   8, 1

# Задание 2.11 (3 балла)

Создайте одномерный массив размерности $200$, в котором каждый элемент - евклидово расстояние между соответствующей строкой `A` и "средней" строкой `A` (средний т.е арифметическое среднее)

In [111]:

# не готово, условие не понято

(200,)

# Задание 2.12 (2 балла)

Создайте новый массив, который состоит из элементов `A`, измененных по следующим правилам:
- если элемент меньше $50$, то он умножается на $2$
- в противном случае он умножается на $3$

Используйте [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

In [85]:
B = np.where(A < 50, A*2, A*3)
B
# готово

array([[ 84,  16,  88, ..., 195, 231, 207],
       [ 90,  56,  34, ..., 273,  52, 156],
       [ 42, 288, 279, ..., 156,  54, 243],
       ...,
       [204,  38, 183, ...,  42,  38, 153],
       [ 12,  34,  56, ...,   8,  62, 294],
       [231,  20,  36, ..., 249, 246,  50]])

# Задание 2.13 (7 баллов)

Разверните массив `A` в одномерный массив. Создайте три новых массива, подсчитав скользящие средние по окнам $3$, $5$, $10$. Найдите сумму этих массивов, выровнив из размерности нулями справа

*Tip: реализуйте функцию, которая считает скользящее среднее. Используйте [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) или [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html)*

# Задание 2.14 (8 баллов)

Постройте график функции $$f(x) = (5  \sin(2x) - \cos^2(x) - 1 + |x^3| - x^2) / (x^2 + 1)$$  

и производной от этой функции.  Найдите минимум с помощью `scipy` и обозначьте его на графике.

# Задание 2.15 (10 баллов)

Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [2]:
from typing import List 

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)   

[0, 4, 4, 0, 0]

Реализуйте данный алгоритм более оптимальным способом на массивах `numpy`, без использования циклов. Проверьте корректность и идентичность алгоритмов семплирования с помощью статистических тестов.

# Задание 2.16 (5 баллов)

Есть следующий алгоритм "случайного блуждания"

In [3]:
import random 

def walk(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += random.choice([-3, -1, 0, 2, 3])

    return cur_position

walk(10_000)

2003

Реализуйте более эффективную версию с помощью `numpy`, сравните производительность (используя, например, magic `timeit`). Воспользовавшись [kdeplot()](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) или аналогами, постройте график распределения значений `walk(10_000)` на каком-то разумном числе запусков. 